version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
