name: Java CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Test with Gradle
        run: ./gradlew --no-daemon --continue test
      - name: Upload test coverage
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e
      - name: Create test summary
        uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5
        with:
          paths: "**/build/test-results/test/*.xml"
        if: always()

  smoke_tests:
    name: Smoke tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          push: false
          load: true
          tags: exercism/java-representer
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
